services:
  - type: web
    name: fluently-core-backend
    env: docker
    plan: free
    dockerContext: ./services/core-backend
    dockerfilePath: ./services/core-backend/Dockerfile
    envVars:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: production
